//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int reviewId { get; set; }
        public int productId { get; set; }
        public string review1 { get; set; }
        public Nullable<int> rating { get; set; }
        public int userId { get; set; }
    }
}
