//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int shopId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> shopStatus { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<int> setComission { get; set; }
    }
}
