//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBuy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webBuyEntities : DbContext
    {
        public webBuyEntities()
            : base("name=webBuyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDiscount> AdminDiscounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comission> Comissions { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopDiscount> ShopDiscounts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Withdraw> Withdraws { get; set; }
    }
}
